### ISSUE TITLE
The bundler yaml file doesn't have components:   schemas: {}

### ISSUE THREAD

**Issue by chenyan71** [networknt/openapi-bundler#7]
components:
  schemas: {}

It is easier to share components between endpoint if they are defined in components section.

**Comment by ddobrin** [comment]
@chenyan71 : should this issue be taken as a recommendation?

There was a bundler issue where, if the comopents : schema : element was missing, the bundler would fail. It has been addressed.

At my current client, all objects are defined in components: schema: and, before bundling, many objects are declared/managed/versioned in shared files, for easy reuse across the organization

**Comment by chenyan71** [comment]
It will generate share components in the components section if use set the type as object in the model yaml file:

      type: object

Close this issue.
